# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Boyner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Boyner

  pod 'Alamofire'
  pod 'Kingfisher'


  target 'BoynerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoynerUITests' do
    # Pods for testing
  end

end
